name: CI/CD Pipeline for React App on Raspberry Pi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy the app to Raspberry Pi
        run: |
          # Ensure the deployment directory exists and is a valid git repo
          if [ ! -d "/var/www/my-react-app/.git" ]; then
            sudo rm -rf /var/www/my-react-app  # Remove any existing non-git folder
            sudo mkdir -p /var/www/my-react-app
            sudo chown -R $USER:$USER /var/www/my-react-app
            git clone https://github.com/CrazySoda/Tanvir-s-Test.git /var/www/my-react-app
          fi
          
          # Navigate to the project directory and pull the latest changes
          cd /var/www/my-react-app
          git pull

          # Install dependencies and build the app
          npm install
          npm run build

          # Restart the app using PM2
          pm2 restart my-react-app || pm2 start npm --name "my-react-app" -- start
